### ISSUE TITLE
Support call cryptosetup by external Pipe 

### ISSUE THREAD

**Issue by petrkr** [xaionaro-go/trezorLuks#2]
Hi,
nice project, I need this one and wanted do it already by trezor-python way. Just do not wanted put all python env to initramfs.

Can you do please some parameter that will only print key to stdout instead call cryptosetup directly? I want use it for full-disk-encryption and also want use Ubuntu-like cryptosetup where I can call external script for password, but can not call trezorLuks instead cryptosetup.

My idea is like you will call something like this:

`trezorEnc --stdout --key "This will show on trezor's screen" | cryptosetup ....`

My problem is I do not know Go well and if you already have this done, maybe it could be easy  for you to do this revision.

Redards Petr

**Comment by xaionaro** [comment]
@petrkr I see, I'll do that soon (may be today or tomorrow) :)

**Comment by xaionaro** [comment]
@petrkr try this: https://github.com/xaionaro-go/trezorCipherKeyValue

```sh
trezorCipherKeyValue --key-name "This will show on trezor's screen" | cryptosetup ....
```

**Comment by cyb3ralbert** [comment]
insane cryptopunks $hit
